services:
  nuxt:
    container_name: nordhealth-interview
    image: node
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NUXT_PORT=3000
      - NUXT_HOST=0.0.0.0
    command: /bin/sh -c "npm install && npm run dev"